# Generated by Django 4.2.7 on 2024-02-24 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_name_user_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
