# Generated by Django 4.2.7 on 2024-01-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, verbose_name='название курса')),
                ('course_preview', models.ImageField(blank=True, null=True, upload_to='education/', verbose_name='превью курса')),
                ('course_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='описание курса')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
            },
        ),
    ]
