# Generated by Django 4.2.7 on 2024-01-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=100, verbose_name='название урока')),
                ('lesson_preview', models.ImageField(blank=True, null=True, upload_to='education/', verbose_name='превью урока')),
                ('lesson_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='описание урока')),
                ('lesson_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='ссылка на урок')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
            },
        ),
    ]
