# Generated by Django 4.2.7 on 2024-01-25 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.course', verbose_name='Урок курса'),
        ),
    ]
