# Generated by Django 4.2.7 on 2024-01-25 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_lesson_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson',
            new_name='course',
        ),
    ]
